name: ir-explorer-prod

services:
  db:
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    restart: always
    command: [ "uv", "run", "litestar", "--app-dir", "app", "run", "-H", "0.0.0.0" ]

  frontend:
    restart: always
    ports:
      - "8204:3000"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        npm run build
        node build

volumes:
  pgdata:
