name: ir-explorer-prod

services:
  db:
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    restart: always
    volumes:
      - ollamadata:/root/.ollama

  backend:
    restart: always

  frontend:
    restart: always
    ports:
      - "8204:8000"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        npm run build
        node build
    environment:
      - PORT=8000
      - ORIGIN=${ORIGIN}

volumes:
  pgdata:
