name: ir-explorer-dev

services:
  db:
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "8101:5432"

  ollama:
    restart: always
    volumes:
      - ollamadata:/root/.ollama
    ports:
      - "8102:11434"

  backend:
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: backend/app
          target: /backend/app
        - action: rebuild
          path: backend/pyproject.toml
    ports:
      - "8103:8000"
    environment:
      - LITESTAR_DEBUG=true

  frontend:
    restart: always
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /frontend/src
        - action: sync
          path: frontend/static
          target: /frontend/static
        - action: rebuild
          path: frontend/package.json
    ports:
      - "8104:5173"
    command: [ "npm", "run", "dev" ]

volumes:
  pgdata:
  ollamadata:
