services:
  db:
    image: paradedb/paradedb
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER?}",
          "-d",
          "${POSTGRES_DB?}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
      - POSTGRES_DB=${POSTGRES_DB?}

  backend:
    build:
      context: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
      - POSTGRES_DB=${POSTGRES_DB?}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  frontend:
    build:
      context: frontend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
